# Theme parameters
colorScheme = "blowfish"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

# Math support using Blowfish's built-in configuration
[library]
  [library.katex]
    enable = true

# mainSections = ["posts", "docs"]
# robots = ""

disableImageOptimization = false
defaultBackgroundImage = "intro_img.jpg" # used as default for background images 
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles

# highlightCurrentMenuArea = true
# smartTOC = true
# smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[homepage]
  layout = "hero" # valid options: page, profile, hero, card, background, custom
  homepageImage = "intro_img.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showHero = true
  heroStyle = "background" 
  showSummary = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showDate = true
  showAuthor = true
  showReadingTime = true
  showPagination = true
  showHeadingAnchors = true

[list]
  showHero = true
  heroStyle = "background"
  showCards = true
  groupByYear = false
  cardView = true

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true 